### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by ChibeMeliodas** [Errored-Innovations/HeadsPlus#110]
### Checklist

- [X] Are you using the latest version/snapshot of [HeadsPlus](https://ci.pluginwiki.us/job/HeadsPlus/)?
- [X] Have you checked to see if others have submitted the same bug report?
- [X] Have you been able to reproduce the bug more then once?

### Description of the bug

Even with all the permissions for the player to craft, it says that it is not possible for the player to do this

I enabled it in the configs, I tried to see if I made a mistake in the HeadBlocks HeadPlus plugin

![Screenshot_1](https://user-images.githubusercontent.com/33189940/220430267-7c279435-d088-43a4-8379-5b5215eebea1.png)
![Screenshot_2](https://user-images.githubusercontent.com/33189940/220430272-3f499c1a-1f65-474a-ac72-7383a7afe7c1.png)
![Screenshot_3](https://user-images.githubusercontent.com/33189940/220430274-c2b1e4d2-cd97-49d7-8584-9a6699ba998a.png)

### Steps To Reproduce

1. I try to craft a custom head
2. gives error, and does not allow the item to go to the inventory
![Screenshot_3](https://user-images.githubusercontent.com/33189940/220430912-d979a039-33e9-40f8-8d12-379d141738d2.png)

**Comment by Thatsmusic99** [comment]
Can you try running `/lp verbose on ChibeMeliodas & headsplus`, try to craft a head and send the results of that here? I just tried to set the permission and it worked without issue.

**Comment by ChibeMeliodas** [comment]
> In the video, I accessed the verbose, the configs quickly, the LuckyPerms place, and I showed the bug occurring inside the game... on the console it doesn't say error or anything.
https://www.mediafire.com/file/e1yh31thap9rwe0/2023-02-21_17-35-34.mp4/file

**Comment by ChibeMeliodas** [comment]
> > In the video, I accessed the verbose, the configs quickly, the LuckyPerms place, and I showed the bug occurring inside the game... on the console it doesn't say error or anything.
> > https://www.mediafire.com/file/e1yh31thap9rwe0/2023-02-21_17-35-34.mp4/file

Sorry, I had to put it on media fire because the video reached 100mb, and here you can only send 10mb

**Comment by Thatsmusic99** [comment]
headsplus.craft.* is not the permission you want to focus on, it'll be headsplus.craft.

Don't worry about sending a second video - just use the command I mentioned, send a screenshot of it whilst using the crafting table and you're good to go.

**Comment by ChibeMeliodas** [comment]
> headsplus.craft.* is not the permission you want to focus on, it'll be headsplus.craft.

yes, but that permission is too!
![image](https://user-images.githubusercontent.com/33189940/220459298-65066017-d120-4a97-896d-7fc94da3776d.png)

**Comment by Thatsmusic99** [comment]
As mentioned, please try the command I mentioned. Otherwise, there's no easy way to tell whether it's a matter of permission setup or a plugin issue.

**Comment by ChibeMeliodas** [comment]
> As mentioned, please try the command I mentioned. Otherwise, there's no easy way to tell whether it's a matter of permission setup or a plugin issue.

that's what I'm trying to tell you, the commands you asked to use, it doesn't appear that the permission was not set, and in the settings and in lp it says it is, so I think it's having 1 error

**Comment by ChibeMeliodas** [comment]
> 

the dropping part works, but the crafting part doesn't

**Comment by Thatsmusic99** [comment]
But then you disabled the verbose before trying to craft without OP, it'll need to be kept enabled when testing. Unless there's a part I'm missing?
