### ISSUE TITLE
[Bug]: HPXHead in the NBT tag

### ISSUE THREAD

**Issue by MacroVoid** [Errored-Innovations/HeadsPlus#117]
### Checklist

- [x] Are you using the latest version/snapshot of [HeadsPlus](https://ci.pluginwiki.us/job/HeadsPlus/)?
- [X] Have you checked to see if others have submitted the same bug report?
- [X] Have you been able to reproduce the bug more then once?

### Description of the bug

If you put display-name: '' in the settings of the player's head, then HPXHead will be used instead of the player's nickname. Please change the player's nickname in the nbt tag

https://github.com/Errored-Innovations/HeadsPlus/assets/166911580/a4d43541-a406-4d0d-bd52-8f3403d4cdf1

### Steps To Reproduce

1) Change the player settings in the mobs.yml file to display-name: ''
2) Get the player's head through command or death

**Comment by Thatsmusic99** [comment]
Checking the demonstration, it still says "MacroVoid's Head" when you break the head - is there something I'm missing?

**Comment by Thatsmusic99** [comment]
Ohh you're right, I'm blind, sorry :') I'll check this shortly

**Comment by Thatsmusic99** [comment]
Github closed this early, but this should be fixed here: https://ci.pluginwiki.us/job/HeadsPlus/163/artifact/target/HeadsPlus-7.1.1.jar
