### ISSUE TITLE
Missing head names [BUG]

### ISSUE THREAD

**Issue by Kismalax** [Errored-Innovations/HeadsPlus#48]
Head names are missing in the /heads head browser after switching to 6.11.7 or 6.11.8.
I can reproduce it with default configs.

6.11.6
![hp-1](https://user-images.githubusercontent.com/50720665/124366910-83689e80-dc53-11eb-902d-26c6a0f601ce.png)

6.11.7/6.11.8
![hp-2](https://user-images.githubusercontent.com/50720665/124366928-9bd8b900-dc53-11eb-8b9a-f4e53a5322f1.png)

### Required information
- Server version: Paper 1.16.5
- HeadsPlus version: 6.11.8
- Using default config
- Uses Vault: yes

**Comment by Thatsmusic99** [comment]
now I just need to figure out how the hell I managed this when I literally didn't touch the mechanics that manage that...

**Comment by Thatsmusic99** [comment]
Should be fixed in upcoming [dev build 37](https://ci.pluginwiki.us/job/HeadsPlus/37/)
