### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by StuffOfSonny** [Errored-Innovations/HeadsPlus#78]
So I got some red text in my Server terminal telling me to send a specific .json file here, but GitHub won't let me attach the file.
Forgive my use of puu.sh
https://puu.sh/IsVdx/7d415d2a9c.json

**Comment by Thatsmusic99** [comment]
Are levels disabled by any chance? Funky error

**Comment by StuffOfSonny** [comment]
> 

Yes, I installed this plugin purely for adding heads as a drop. I didn't want any fancy crafting or challenges, because I also run Geyser and I didn't know/want to find out how Bedrock handles it.

**Comment by Thatsmusic99** [comment]
Gotcha, cheers for that, I'll take a look at that error when I can.

**Comment by TNTUP** [comment]
can confirm this, there's like 690+ json files in debug
[12.05.2021 02_10_10-REPORT-0.txt](https://github.com/Errored-Innovations/HeadsPlus/files/7655396/12.05.2021.02_10_10-REPORT-0.txt)
/

lol renamed json to txt

**Comment by Thatsmusic99** [comment]
Forgot to update this, my mistake - this was fixed in one of the recent dev builds (I believe 38, most recent is 40)
