### ISSUE TITLE
[BUG] Exception - right click block?

### ISSUE THREAD

**Issue by OverlordFreddo** [Errored-Innovations/HeadsPlus#79]
## FIRST-HAND CHECK - ARE YOU USING THE LATEST VERSION/SNAPSHOT OF HEADSPLUS? Have you checked to see if others have submitted the same bug report? 
Yes, 7.0.0-MVP-1

### Description of the bug
Console error

### To Reproduce
I do not know because I was afk

### Have you been able to reproduce the bug more than once?
Not yet
### Expected behavior
See reproduction

### Has a debug report been generated? 
If you have a debug report, go to plugin/HeadsPlus/debug, copy your report onto pastebin or hastebin, and paste it here, but also skip to the bottom question (additional information). If you don't, fill in the information below.
{
  "Special message": "Off with your head!",
  "Locale": "en_us",
  "HeadsPlus version": "7.0.0-MVP-1",
  "Date": "12/05/2021 00:03:02",
  "Has Vault hooked": true,
  "Other Plugins": [
    "Sickle-1.8.3 (1.13)",
    "Scoreboard-2.1.0 (1.16)",
    "ChestSort-12.1.0 (1.13)",
    "RHLeafDecay-1.17_R1 (1.13)",
    "ViaVersion-4.1.1 (1.13)",
    "ColoredAnvils-2.0.0 (1.17)",
    "ViaBackwards-4.1.1 (1.13)",
    "LuckPerms-5.3.87 (1.13)",
    "Vault-1.7.3-b131 (1.13)",
    "WorldEdit-7.2.8-SNAPSHOT+6003-6e106c1 (1.13)",
    "Essentials-2.19.1-dev+49-d091d69 (1.13)",
    "Multiverse-Core-4.3.2-SNAPSHOT-b867 (1.13)",
    "WorldGuard-7.0.7-SNAPSHOT+2165-81750e1 (1.17)",
    "Multiverse-Inventories-4.2.3-SNAPSHOT-b519 (1.13)",
    "EssentialsChat-2.19.1-dev+49-d091d69 (1.13)",
    "mcMMO-2.1.205 (1.13)",
    "Multiverse-Portals-4.2.2-SNAPSHOT-b850 (1.13)",
    "EssentialsSpawn-2.19.1-dev+49-d091d69 (1.13)",
    "CoreProtect-20.1 (1.13)",
    "Harbor-1.6.3 (1.14)",
    "EssentialsDiscord-2.19.1-dev+49-d091d69 (1.13)",
    "WorldBorder-2.1.4 (1.15)",
    "LWC-2.2.7-ad0f824 (1.13)",
    "HeadsPlus-7.0.0-MVP-1 (1.13)",
    "LWCTrust-1.0.6 (1.13)",
    "Plan-5.4 build 1516 (1.13)",
    "Multiverse-NetherPortals-4.2.2-SNAPSHOT-b804 (1.13)",
    "ChestShop-3.12.1-SNAPSHOT (build 334) (1.13)"
  ],
  "Error Information": {
    "is-skull": "true",
    "action": "RIGHT_CLICK_BLOCK",
    "Exception": [
      "java.lang.NullPointerException: Cannot invoke \"com.mojang.authlib.GameProfile.getName()\" because \"profile\" is null",
      "at HeadsPlus-7.0.0-MVP-1.jar//io.github.thatsmusic99.headsplus.config.ConfigInteractions.getMessageForHead(ConfigInteractions.java:125)",
      "at HeadsPlus-7.0.0-MVP-1.jar//io.github.thatsmusic99.headsplus.listeners.HeadInteractListener.onEvent(HeadInteractListener.java:54)",
      "at HeadsPlus-7.0.0-MVP-1.jar//io.github.thatsmusic99.headsplus.listeners.HeadInteractListener.onEvent(HeadInteractListener.java:18)",
      "at HeadsPlus-7.0.0-MVP-1.jar//io.github.thatsmusic99.headsplus.util.events.HeadsPlusEventExecutor.execute(HeadsPlusEventExecutor.java:37)",
      "at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)",
      "at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)",
      "at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)",
      "at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:543)",
      "at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:540)",
      "at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1754)",
      "at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:33)",
      "at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:9)",
      "at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)",
      "at net.minecraft.server.TickTask.run(TickTask.java:18)",
      "at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:149)",
      "at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.c(IAsyncTaskHandlerReentrant.java:23)",
      "at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1413)",
      "at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189)",
      "at net.minecraft.util.thread.IAsyncTaskHandler.y(IAsyncTaskHandler.java:122)",
      "at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1391)",
      "at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1384)",
      "at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:132)",
      "at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1362)",
      "at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1268)",
      "at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)",
      "at java.base/java.lang.Thread.run(Thread.java:833)\r\n"
    ]
  }
}
### Required information
- Server version: 1.18 Paper build 36
- HeadsPlus version: 7.0.0-MVP-1
- Whether or not the plugin uses MySQL Flatfile
- Server type (e.g Spigot, Paper): Paper
- Uses Vault: Yes
- Any other pieces of information that may be required.
You tell me :)

Sorry this might not be much to go on, unless you know the cause already.  Ask for more info

(Apologies for the weird title change - I am rather tired)

**Comment by Thatsmusic99** [comment]
Already reported in Discord and fixed locally, will try and push today

**Comment by OverlordFreddo** [comment]
> Already reported in Discord and fixed locally, will try and push today

Fantastic cheers.
