### ISSUE TITLE
/hpc

### ISSUE THREAD

**Issue by rkfsociety** [Errored-Innovations/HeadsPlus#83]
[Sat, 11. Dec 2021 13:51:29 MSK INFO] rkfsociety issued server command: /hpc
[Sat, 11. Dec 2021 13:51:29 MSK WARN] java.lang.NullPointerException: Cannot invoke "io.github.thatsmusic99.configurationmaster.api.ConfigFile.getInteger(String)" because "this.hpi" is null
[Sat, 11. Dec 2021 13:51:29 MSK WARN] at HeadsPlus-7.0.1.jar//io.github.thatsmusic99.headsplus.inventories.BaseInventory.<init>(BaseInventory.java:60)
[Sat, 11. Dec 2021 13:51:29 MSK WARN] at HeadsPlus-7.0.1.jar//io.github.thatsmusic99.headsplus.inventories.list.ChallengesMenu.<init>(ChallengesMenu.java:16)
[Sat, 11. Dec 2021 13:51:29 MSK WARN] at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[Sat, 11. Dec 2021 13:51:29 MSK WARN] at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[Sat, 11. Dec 2021 13:51:29 MSK WARN] at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[Sat, 11. Dec 2021 13:51:29 MSK WARN] at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[Sat, 11. Dec 2021 13:51:29 MSK WARN] at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[Sat, 11. Dec 2021 13:51:29 MSK WARN] at HeadsPlus-7.0.1.jar//io.github.thatsmusic99.headsplus.inventories.InventoryManager$InventoryType.getInventory(InventoryManager.java:37)
[Sat, 11. Dec 2021 13:51:29 MSK WARN] at HeadsPlus-7.0.1.jar//io.github.thatsmusic99.headsplus.inventories.InventoryManager.open(InventoryManager.java:190)
[Sat, 11. Dec 2021 13:51:29 MSK WARN] at HeadsPlus-7.0.1.jar//io.github.thatsmusic99.headsplus.commands.ChallengeCommand.onCommand(ChallengeCommand.java:33)
[Sat, 11. Dec 2021 13:51:29 MSK WARN] at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[Sat, 11. Dec 2021 13:51:29 MSK WARN] at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[Sat, 11. Dec 2021 13:51:29 MSK WARN] at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchCommand(CraftServer.java:876)
[Sat, 11. Dec 2021 13:51:34 MSK WARN] at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2267)
[Sat, 11. Dec 2021 13:51:34 MSK WARN] at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2078)
[Sat, 11. Dec 2021 13:51:34 MSK WARN] at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2059)
[Sat, 11. Dec 2021 13:51:34 MSK WARN] at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[Sat, 11. Dec 2021 13:51:34 MSK WARN] at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[Sat, 11. Dec 2021 13:51:34 MSK WARN] at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
[Sat, 11. Dec 2021 13:51:34 MSK WARN] at net.minecraft.server.TickTask.run(TickTask.java:18)
[Sat, 11. Dec 2021 13:51:34 MSK WARN] at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:149)
[Sat, 11. Dec 2021 13:51:34 MSK WARN] at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.c(IAsyncTaskHandlerReentrant.java:23)
[Sat, 11. Dec 2021 13:51:34 MSK WARN] at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1413)
[Sat, 11. Dec 2021 13:51:34 MSK WARN] at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189)
[Sat, 11. Dec 2021 13:51:34 MSK WARN] at net.minecraft.util.thread.IAsyncTaskHandler.y(IAsyncTaskHandler.java:122)
[Sat, 11. Dec 2021 13:51:34 MSK WARN] at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1391)
[Sat, 11. Dec 2021 13:51:34 MSK WARN] at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1384)
[Sat, 11. Dec 2021 13:51:34 MSK WARN] at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:132)
[Sat, 11. Dec 2021 13:51:34 MSK WARN] at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1362)
[Sat, 11. Dec 2021 13:51:34 MSK WARN] at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1268)
[Sat, 11. Dec 2021 13:51:39 MSK WARN] at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[Sat, 11. Dec 2021 13:51:39 MSK WARN] at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Thatsmusic99** [comment]
Already covered in #82
