### ISSUE TITLE
[BUG] Bug reports from my console log. Said to submit log files here.

### ISSUE THREAD

**Issue by Andarius68** [Errored-Innovations/HeadsPlus#84]
## FIRST-HAND CHECK - ARE YOU USING THE LATEST VERSION/SNAPSHOT OF HEADSPLUS? Have you checked to see if others have submitted the same bug report? 
State here when you have checked the following points above.

### To Reproduce
1. ...
2. ...
3. ...

### Expected behavior
[BugReports.zip](https://github.com/Errored-Innovations/HeadsPlus/files/7713059/BugReports.zip)

### Has a debug report been generated? 
If you have a debug report, go to plugin/HeadsPlus/debug, copy your report onto pastebin or hastebin, and paste it here, but also skip to the bottom question (additional information). If you don't, fill in the information below.

### Required information
- Server version:
- HeadsPlus version:
- Whether or not the plugin uses MySQL
- Server type (e.g Spigot, Paper):
- Uses Vault:
- Any other pieces of information that may be required.

## Additional information
Add any other information/notes you'd like to add at the bottom

**Comment by Thatsmusic99** [comment]
Seems to be floodgate doing something dodgy again, when I have access to the proper tools for the job I'll get back on this.

**Comment by Andarius68** [comment]
Thank you.

**Comment by Thatsmusic99** [comment]
Unable to reproduce. There is a similar investigation with this going on in AT where I suspect that the floodgate players aren't being properly tracked, making it an issue on floodgate's end. But I don't want to go pushing it on them without confirming that it is a problem on their end.
