### ISSUE TITLE
Player head lore showing default lore

### ISSUE THREAD

**Issue by SideLo98** [Errored-Innovations/HeadsPlus#85]
## FIRST-HAND CHECK - ARE YOU USING THE LATEST VERSION/SNAPSHOT OF HEADSPLUS? Have you checked to see if others have submitted the same feature request? 
yes currently 7.0.2 is latest version

### Description of request
A minor improvement for Player Heads Lore and/or display-name. It doesn't actually displays exact lore as defined in mobs.yml for player instead it displays the default lore. "Type » {type}" instead of "Player: {player}".

### To ensure that the plugin stays original, HeadsPlus will not be taking requests that already exist within actively updated plugins, such as HeadsDatabase and LeaderHeads (this one of which is not close to HeadsPlus whatsoever and shares no features, however is often mistaken as that).
Yes I agree it's HeadsPlus

### Additional information
Some screenshots: 
![image](https://user-images.githubusercontent.com/67060780/146106836-42900e23-ef36-4967-9aa6-56d4248927cc.png)
![image](https://user-images.githubusercontent.com/67060780/146106840-d9ce5dd4-573b-4dfd-8361-bce48b8031b4.png)
![image](https://user-images.githubusercontent.com/67060780/146106896-40269dc7-ac37-4988-a29a-437ce42823a2.png)

**Comment by Thatsmusic99** [comment]
Seems to be a bug rather than a feature request

**Comment by Thatsmusic99** [comment]
Should be fixed in the most recent dev build: https://ci.pluginwiki.us/job/HeadsPlus/61/artifact/target/HeadsPlus-7.0.3+DEV_61.jar
