### ISSUE TITLE
[BUG] Player head price according to balance shows extra decimal format

### ISSUE THREAD

**Issue by SideLo98** [Errored-Innovations/HeadsPlus#87]
## FIRST-HAND CHECK - ARE YOU USING THE LATEST VERSION/SNAPSHOT OF HEADSPLUS? Have you checked to see if others have submitted the same bug report? 
Yes currently 7.0.2 is latest version

### Description of the bug
when using [adjust-price-according-to-balance: true] it displays way too extra value after decimal and doesnt respect the default [price-decimal-format: '#,###.##'] format.

### To Reproduce
1. enable [adjust-price-according-to-balance: true].
2. use either killer/victim's balance doesnt matter and percentage can be anything (in my case it's 100) to display.
3. let someone kill you to obtain your head with your balance as price in it.

### Have you been able to reproduce the bug more than once?
Yes

### Expected behavior
It should either display no digits after decimal or max 2 digits as defined in [price-decimal-format: '#,###.##'].

### Screenshots
![image](https://user-images.githubusercontent.com/67060780/146478403-1a907633-4334-4b78-85c2-e42c3ad162e9.png)
![image](https://user-images.githubusercontent.com/67060780/146478449-c8ec4218-774e-40c0-b7d2-f6ad00eb5600.png)

### Has a debug report been generated? 
If you have a debug report, go to plugin/HeadsPlus/debug, copy your report onto pastebin or hastebin, and paste it here, but also skip to the bottom question (additional information). If you don't, fill in the information below.

### Required information
- Server version: 1.17.1
- HeadsPlus version: 7.0.2
- Whether or not the plugin uses MySQL: No MySQL
- Server type (e.g Spigot, Paper): Paper
- Uses Vault: Yes
- Any other pieces of information that may be required.

## Additional information
Sorry if I missed some info, I can provide in comments if needed.

**Comment by Thatsmusic99** [comment]
Should be fixed in [this dev build](https://ci.pluginwiki.us/job/HeadsPlus/55/artifact/target/HeadsPlus-7.0.3+DEV_55.jar), lemme know if it works.

**Comment by SideLo98** [comment]
> 

It is fixed in the dev build yes.
