### ISSUE TITLE
eco balance[BUG]

### ISSUE THREAD

**Issue by Yamiru** [Errored-Innovations/HeadsPlus#88]
## FIRST-HAND CHECK - ARE YOU USING THE LATEST VERSION/SNAPSHOT OF HEADSPLUS? Have you checked to see if others have submitted the same bug report?  yes
State here when you have checked the following points above.

### Description of the bug
If I buy head not take moneys from balance.

### To Reproduce
1. command /heads
2. buying items
3. adding to my inventory
4. not take money

### Have you been able to reproduce the bug more than once?
yes
### Expected behavior
taking money from balance

### Screenshots
no errors no console errors

### Has a debug report been generated? 
If you have a debug report, go to plugin/HeadsPlus/debug, copy your report onto pastebin or hastebin, and paste it here, but also skip to the bottom question (additional information). If you don't, fill in the information below.

### Required information
- Server version: 1.18 paper latest
- HeadsPlus version: 7.0.2 latest
- Whether or not the plugin uses MySQL: NO
- Server type (e.g Spigot, Paper): Paper
- Uses Vault: yes (I tryed ultraeconomy, cmi economy,...)

## Additional information
Add any other information/notes you'd like to add at the bottom
used other economy but same problem, all plugins 4 works with vault economy only headsplus not

**Comment by Thatsmusic99** [comment]
You're most likely OPed. I could buy heads just fine whilst de-OPed. Please make sure the permission `headsplus.bypass.cost` is negated.

If you need any help regarding this, feel free to ask in the support Discord.
