### ISSUE TITLE
[Bug]: Plyaer head valeu

### ISSUE THREAD

**Issue by kedavlar** [Errored-Innovations/HeadsPlus#96]
### Checklist

- [X] Are you using the latest version/snapshot of [HeadsPlus](https://ci.pluginwiki.us/job/HeadsPlus/)?
- [X] Have you checked to see if others have submitted the same bug report?
- [X] Have you been able to reproduce the bug more then once?

### Description of the bug

When i try to sell player head, i always get base value of 100 instead of the real value displayed on the lore

### Steps To Reproduce

drop player head

sell the head

**Comment by Thatsmusic99** [comment]
Apologies about the delay on this - it'll be fixed in the next dev build.
